#!/usr/bin/env bash
#
# Monitor EvoClaw trial progress across all repos.
#
# Usage:
#   ./scripts/monitor.sh <trial_name>                          # monitor a trial
#   ./scripts/monitor.sh <trial_name> --repos navidrome dubbo  # monitor specific repos
#   ./scripts/monitor.sh <trial_name> --data-root /path/to/data
#
# This script auto-generates a config from trial_config.yaml (or --data-root)
# and runs collect_results.py --multi-repo.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$PROJECT_ROOT/.evoclaw"

# ─────────────────────────────────────────────
# Parse arguments
# ─────────────────────────────────────────────
TRIAL_NAME=""
DATA_ROOT=""
REPOS=()
EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --data-root)  DATA_ROOT="$2"; shift 2 ;;
        --repos)      shift; while [[ $# -gt 0 ]] && [[ "$1" != --* ]]; do REPOS+=("$1"); shift; done ;;
        --help|-h)
            echo "Usage: $0 <trial_name> [--data-root PATH] [--repos REPO ...] [-- extra args]"
            echo ""
            echo "  <trial_name>        Name of the trial to monitor (required)"
            echo "  --data-root PATH    Path to EvoClaw-data (default: from trial_config.yaml)"
            echo "  --repos REPO ...    Only show these repos"
            echo "  -- ...              Extra args passed to collect_results.py"
            exit 0
            ;;
        --)           shift; EXTRA_ARGS=("$@"); break ;;
        --*)          EXTRA_ARGS+=("$1"); shift ;;
        *)
            if [[ -z "$TRIAL_NAME" ]]; then
                TRIAL_NAME="$1"; shift
            else
                EXTRA_ARGS+=("$1"); shift
            fi
            ;;
    esac
done

if [[ -z "$TRIAL_NAME" ]]; then
    echo "Error: trial_name is required"
    echo "Usage: $0 <trial_name> [--data-root PATH] [--repos REPO ...]"
    exit 1
fi

# ─────────────────────────────────────────────
# Resolve data_root
# ─────────────────────────────────────────────
if [[ -z "$DATA_ROOT" ]]; then
    # Try reading from trial_config.yaml
    EVOCLAW_CONFIG="$PROJECT_ROOT/trial_config.yaml"
    if [[ -f "$EVOCLAW_CONFIG" ]]; then
        DATA_ROOT=$(python3 -c "
import yaml
with open('$EVOCLAW_CONFIG') as f:
    cfg = yaml.safe_load(f)
print(cfg.get('data_root', ''))
" 2>/dev/null)
    fi
    if [[ -z "$DATA_ROOT" ]]; then
        echo "Error: --data-root not specified and no data_root found in trial_config.yaml"
        exit 1
    fi
fi

# Resolve to absolute path
DATA_ROOT="$(cd "$DATA_ROOT" 2>/dev/null && pwd)" || { echo "Error: data_root not found: $DATA_ROOT"; exit 1; }

# ─────────────────────────────────────────────
# Auto-generate config
# ─────────────────────────────────────────────
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/${TRIAL_NAME}_collect.py"

# Discover repos (directories with metadata.json)
REPO_ENTRIES=""
for repo_dir in "$DATA_ROOT"/*/; do
    [[ ! -f "$repo_dir/metadata.json" ]] && continue
    repo_name=$(basename "$repo_dir")

    # If --repos specified, filter
    if [[ ${#REPOS[@]} -gt 0 ]]; then
        matched=false
        for r in "${REPOS[@]}"; do
            if [[ "$repo_name" == *"$r"* ]]; then
                matched=true
                break
            fi
        done
        $matched || continue
    fi

    REPO_ENTRIES+="    \"$repo_name\": {\"path\": \"$repo_name\"},
"
done

# Ensure trial name has _NNN suffix (matching run_all.py convention)
if ! [[ "$TRIAL_NAME" =~ _[0-9]{3}$ ]]; then
    TRIAL_NAME="${TRIAL_NAME}_001"
fi

cat > "$CONFIG_FILE" << PYEOF
# Auto-generated by monitor.sh for trial: $TRIAL_NAME
DATA_ROOT = "$DATA_ROOT"

WORKSPACE_MAPPING = {
$REPO_ENTRIES}

E2E_TRIAL_NAMES = ["$TRIAL_NAME"]
PYEOF

# ─────────────────────────────────────────────
# Run collect_results
# ─────────────────────────────────────────────
cd "$PROJECT_ROOT"

COLLECT_ARGS=(
    python3 -m harness.e2e.collect_results
    --multi-repo
    --config "$CONFIG_FILE"
    --trial-type e2e
)

# --repos filtering is already applied in the generated WORKSPACE_MAPPING,
# so we don't pass --config-repos (which requires exact key match).

# Append extra args
if [[ ${#EXTRA_ARGS[@]} -gt 0 ]]; then
    COLLECT_ARGS+=("${EXTRA_ARGS[@]}")
fi

exec "${COLLECT_ARGS[@]}"
